# Site settings
title:       derek hubbard
email:       derek@derekhubbard.com
author:      Derek Hubbard
description: "think. code. blog."
baseurl:     ""
url:         "/"

# Google analytics
google_analytics: UA-9397993-1

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  true

# Social icons
show_social_icons: true
github_username: derekhubbard
twitter_username: derekhubbard
google_plus_id:
linkedin_username: derekhubbard
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     10

sass:
  compressed: true

gems: [jekyll-paginate]
