# Site settings
title:       derek hubbard
email:       derek@derekhubbard.com
author:      Derek Hubbard
description: "a creative and inquisitive software engineer with over 15 years of experience developing exceptional user interfaces and first-class products"
baseurl:     ""
url:         "/"

# Google analytics
google_analytics: UA-9397993-1

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  true

# Social icons
show_social_icons: true
github_username: derekhubbard
twitter_username: derekhubbard
google_plus_id:
linkedin_username: derekhubbard
bitcoin_url:
paypal_url:
flattr_button:
instagram_username: derekhubbard
facebook_username: thederekhubbard
dribbble_username: derekhubbard

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     10

sass:
  compressed: true
  sass_dir: assets/sass

gems: [jekyll-paginate]
