# Site settings
title:       derekhubbard.com
email:       derek@derekhubbard.com
author:      Derek Hubbard
description: "think. code. blog."
baseurl:     ""
url:         "http://derekhubbard.com"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true 
github_username: derekhubbard
twitter_username: derekhubbard
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
